# NumPy
* http://www.numpy.org
* http://docs.scipy.org/doc/numpy-dev/genindex.html

In [1]:
import numpy as np

## 값으로 생성
* ndarray 생성하는 가장 간단한 방법
* `np.array(list [, dtyle])`
    * dtype
        * int: int8, int16, int32
        * uint : uint8, uint16, uint32, uint64
        * float : float16, float32, float64, float128
        * complex: complex64, complex128, complex256
        * bool : bool
* 전달한 값에 따라 dtype 결정
* 명시적 dtype 지정

In [2]:
a = np.array([1,2,3,4])
b = np.array([[1,2,3,4], [5,6,7,8]])
c = np.array([1,2,3.14,4])
d = np.array([1,2,3,4], dtype=np.float32)
print(a, a.dtype, a.shape)
print(b, b.dtype, b.shape)
print(c, c.dtype, c.shape)
print(d, d.dtype, d.shape)

[1 2 3 4] int64 (4,)
[[1 2 3 4]
 [5 6 7 8]] int64 (2, 4)
[1.   2.   3.14 4.  ] float64 (4,)
[1. 2. 3. 4.] float32 (4,)


## ndarray 속성
* ndim : 차원(축)의 수
* shape : 각 차원의 크기, 튜플
* size : 전체 요소의 갯수
* dtype : 요소의 데이타 타입
* itemsize : 각 요소의 바이트 크기

In [3]:
print(a.ndim, a.shape, a.size, a.dtype, a.itemsize)
print(b.ndim, b.shape, b.size, b.dtype, b.itemsize)
print(c.ndim, c.shape, c.size, c.dtype, c.itemsize)
print(d.ndim, d.shape, d.size, d.dtype, d.itemsize)

1 (4,) 4 int64 8
2 (2, 4) 8 int64 8
1 (4,) 4 float64 8
1 (4,) 4 float32 4


## 크기와 초기 값으로 생성
* np.empty( tuple [, dtype] ) : 쓰레기 값으로 초기화된 배열 생성
* np.zeros( tuple [, dtype] ) : 0으로 초기화된 배열 생성
* np.ones( tuple [, dtype] ) : 1로 초기화된 배열 생성
* np.full( tuple, fill_value [, dtype] ) : fill_value로 초기화된 배열 생성

In [4]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
print(a.shape, a.ndim, a.size, a.dtype)

(2, 3) 2 6 float64


In [6]:
b = np.zeros((2,3,4), dtype=np.uint8)
b

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=uint8)

In [7]:
c = np.ones((2,3), dtype=np.float32)
c

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [8]:
d = np.empty((2,3))
d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
e = np.empty((2,3), dtype=np.float32)
e

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [10]:
f = np.full((2,3),255)
f

array([[255, 255, 255],
       [255, 255, 255]])

## 시퀀스와 난수로 생성
* np.arange([start=0, ] stop [, step=1, dtype=float64])
    * start : 시작 값
    * stop : 종료 값, 범위에 포함하는 수는 stop - 1 까지
    * step : 증가 값
    * dtype : 데이타 타입
* np.random.rand([d0 [d1 [...dn]]])
    * d0,d1 ... dn : shape, 생략하면 난수 1개
* np.random.randn([d0 [d1 [...dn]]])
    * 평균=0, 분산=1, 표준정규 분포를 따르는 무작위 수

In [11]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [12]:
b = np.arange(5.0)
b

array([0., 1., 2., 3., 4.])

In [13]:
c = np.arange(3,9, 2)
c

array([3, 5, 7])

In [14]:
e = np.random.rand()
e

0.24851633795711225

In [15]:

f = np.random.randn()
f

0.29996525240555727

In [16]:
g = np.random.randn(2,3)
g

array([[-0.34166035, -0.54382366, -0.06574906],
       [-0.47509238,  0.1098207 ,  1.74254508]])

In [17]:
h = np.random.randn(2,3)
h

array([[-0.41111503,  1.01292735,  0.97888679],
       [ 0.34749092,  0.94755752, -1.46602834]])

## 기존 배열로 생성
* np.empty_like(array [, dtype])
* np.zeros_lie(array [, dtype])
* np.ones_like(array [, dtype])
* ones_like(array, fill_value [, dtype])


In [18]:
aa = np.empty_like(a)
aa

array([                  0, 4607182418800017408, 4611686018427387904,
       4613937818241073152, 4616189618054758400])

In [19]:
bb = np.zeros_like(b)
bb

array([0., 0., 0., 0., 0.])

In [20]:
cc = np.ones_like(c)
cc

array([1, 1, 1])

In [21]:
dd = np.full_like(d, 125)
dd

array([[125., 125., 125.],
       [125., 125., 125.]])

## dtype 변경
* ndarray.astype(dtype)
  * dtype : 변경하고 싶은 dtype, 문자열 또는 dtype
* numpy.uint*XX* (array): array를 부호 없는 정수(uint) 타입으로 변경해서 반환
  * uint*XX* : uint8, unit16, uint32, uint64
* numpy.int*XX*(array): array를 int 타입으로 변경해서 반환
  * int*XX* : int8, int16, int32, int64
* numpy.float*XX*(array) : array를 float 타입으로 변경해서 반환
  * float*XX* : float16, float32, float32, float64, float128
* numpy.complex*XX*(array) : array를 복소수(complex) 타입으로 변경해서 반환
  * complex*XX* : complex64, complex128, complex256


In [22]:
a = np.arange(10)
b = a.astype('float32')
print(a, b)


[0 1 2 3 4 5 6 7 8 9] [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [23]:
c = np.uint8(b)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [24]:
d = c.astype(np.float32)
d

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

## 차원 변경

* ndarray.reshape(newshape)
  * ndarray : 원본 배열 객체
  * newshape : 변경하고자 하는 새로운 shape, 튜블
* numpy.reshape(ndarray, newshape)
* numpy.ravel(ndarray)
  * 1차원 배열로 변경
* ndarray.T : 전치배열(Transpose)


In [25]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [26]:
b = a.reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
c = np.reshape(a, (2,3))
c

array([[0, 1, 2],
       [3, 4, 5]])

* -1은 알아서 계산하라는 의미

In [28]:
d = np.arange(100).reshape(2, -1)
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [29]:
d.shape

(2, 50)

In [30]:
e = np.arange(100).reshape(-1, 5)
e

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [31]:
e.shape

(20, 5)

* 1차원으로 변경하는 3가지 방법
    * reshape(n)
    * reshape(-1)
    * ravel()

In [32]:
f = np.zeros((2,3))
f

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
f.reshape((6,))

array([0., 0., 0., 0., 0., 0.])

In [34]:
f.reshape(-1)

array([0., 0., 0., 0., 0., 0.])

In [35]:
np.ravel(f)

array([0., 0., 0., 0., 0., 0.])

* 전치 행렬 T

In [175]:
g = np.arange(10).reshape(2,-1)
g

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [176]:
g.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

## Broadcasting 연산
* 파이썬 리스트의 각 항목을 1씩 증가시키려면 아래 처럼 loop 를 사용해야 한다.

In [38]:
mylist = list(range(10))
mylist

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [39]:
for i in range(len(mylist)):
     mylist[i] = mylist[i] + 1
mylist

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

* 브로드캐스팅 연산으로 한번의 연산으로 가능하다.

In [40]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [43]:
a + 5

array([5, 6, 7, 8, 9])

In [44]:
a - 2

array([-2, -1,  0,  1,  2])

In [45]:
a * 2

array([0, 2, 4, 6, 8])

In [46]:
a / 2

array([0. , 0.5, 1. , 1.5, 2. ])

In [47]:
a ** 2

array([ 0,  1,  4,  9, 16])

In [48]:
b = np.arange(6).reshape(2, -1)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [49]:
b * 2

array([[ 0,  2,  4],
       [ 6,  8, 10]])

* 산술연산 뿐만 아니라 비교 연산도 가능하다.

In [50]:
a

array([0, 1, 2, 3, 4])

In [51]:
a > 2


array([False, False, False,  True,  True])

* 배열과 배열간의 연산도 가능하다.

In [52]:
a = np.arange(10, 60, 10)
b = np.arange(1, 6)

In [53]:
a

array([10, 20, 30, 40, 50])

In [54]:
b

array([1, 2, 3, 4, 5])

In [55]:
a + b

array([11, 22, 33, 44, 55])

In [56]:
a - b

array([ 9, 18, 27, 36, 45])

In [57]:
a * b

array([ 10,  40,  90, 160, 250])

In [58]:
a / b

array([10., 10., 10., 10., 10.])

In [59]:
a ** b

array([       10,       400,     27000,   2560000, 312500000])

* 배열간의 연산에서 두 배열의 shape이 일치하지 않으면 에러 발생

In [60]:
a = np.ones((2,3))
b = np.ones((3,2))
a + b


ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

* shape이 달라도 1축의 길이가 같으면 가능

In [177]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [178]:
c = np.arange(3)
c

array([0, 1, 2])

In [62]:
a + c

array([[1., 2., 3.],
       [1., 2., 3.]])

* 첫번째 축의 길이가 다르면 오류 발생

In [63]:
d = np.arange(2)
a + d


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

* 첫번째 축의 길이가 같으면 정상 실행

In [64]:
a
d = np.arange(2).reshape(2,1)
d

array([[0],
       [1]])

In [65]:
a + d

array([[1., 1., 1.],
       [2., 2., 2.]])

## 인덱싱과 슬라이싱
* 하나의 엘레먼트에 접근하려 할때 해당 인덱스로 접근

In [181]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [182]:
a[5]

5

* n 차원의 경우 n개의 인덱스가 주어지지 않으면 해당 축의 요소를 반환

In [183]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [184]:
b[1]

array([4, 5, 6, 7])

In [185]:
b[1,2]

6

In [186]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [187]:
a[5] = 9
a

array([0, 1, 2, 3, 4, 9, 6, 7, 8, 9])

In [188]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [189]:
b[0] = 0
b

array([[ 0,  0,  0,  0],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
b[1,2] = 99
b


array([[ 0,  0,  0,  0],
       [ 4,  5, 99,  7],
       [ 8,  9, 10, 11]])

In [74]:
a = np.arange(10);
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
a[2:5]

array([2, 3, 4])

In [76]:
a[5:]

array([5, 6, 7, 8, 9])

In [77]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [79]:
b[0:2, 1]

array([1, 5])

In [80]:
b[0:2, 1:3]

array([[1, 2],
       [5, 6]])

In [81]:
b[2, : ]

array([ 8,  9, 10, 11])

In [82]:
b[:, 1]

array([1, 5, 9])

In [83]:
b[0:2, 1:3] = 0
b

array([[ 0,  0,  0,  3],
       [ 4,  0,  0,  7],
       [ 8,  9, 10, 11]])

In [84]:
bb = b[0:2, 1:3]
bb

array([[0, 0],
       [0, 0]])

In [85]:
bb[0] = 99       
b

array([[ 0, 99, 99,  3],
       [ 4,  0,  0,  7],
       [ 8,  9, 10, 11]])

## 팬시 인덱싱
* 배열의 인덱스에 다른 배열을 전달해서 원하는 요소를 선택하는 방법
* 인덱스 또는 불리언(True 만 선택)

In [86]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [87]:
a[[1,3]]

array([1, 3])

In [88]:
a[[True, False, True, False, True]]

array([0, 2, 4])

In [89]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

* 조건식을 직접 인덱스에 넣어도 가능하다

In [90]:
b = a > 5
b

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [91]:
a[b]

array([6, 7, 8, 9])

In [92]:
a[a>5]

array([6, 7, 8, 9])

In [93]:
a[a>5] =1
a

array([0, 1, 2, 3, 4, 5, 1, 1, 1, 1])

In [94]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [95]:
b[[0,2]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [96]:
b[[0,2], [2,3]]

array([ 2, 11])

## 병합과 분리
* numpy.hstack(arrays) : arrays 배열을 수평으로 병합
* numpy.vstack(arrays) : arrays 배열을 수직으로 병합
* numpy.concatenate(arrays, axis=0) :  arrays 배열을 지정한 축 기준으로 병합
* numpy.stack( arrays, axis=0) : arrays 배열을 새로운 축으로 병합
  * arrays : 병합 대상 배열, 튜플


In [97]:
a = np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [98]:
b = np.arange(10, 14).reshape(2,2)
b

array([[10, 11],
       [12, 13]])

In [99]:
np.vstack( (a,b) )

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13]])

In [100]:
np.hstack( (a,b) )

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13]])

* 축번호를 지정하는 것이 중요하다.

In [101]:
np.concatenate((a,b), 0)

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13]])

In [102]:
np.concatenate((a,b), 1)

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13]])

In [103]:
a = np.arange(12).reshape(4,3)
b = np.arange(10, 130, 10).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [104]:
b

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

* stack()은 지정한 축번호가 새로 추가된다.

In [105]:
c = np.stack( (a,b), 0)
c.shape

(2, 4, 3)

In [106]:
c

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90],
        [100, 110, 120]]])

In [107]:
d = np.stack( (a,b), 1)
d.shape

(4, 2, 3)

In [108]:
d

array([[[  0,   1,   2],
        [ 10,  20,  30]],

       [[  3,   4,   5],
        [ 40,  50,  60]],

       [[  6,   7,   8],
        [ 70,  80,  90]],

       [[  9,  10,  11],
        [100, 110, 120]]])

In [109]:
e = np.stack( (a,b), 2)
e.shape

(4, 3, 2)

In [110]:
e

array([[[  0,  10],
        [  1,  20],
        [  2,  30]],

       [[  3,  40],
        [  4,  50],
        [  5,  60]],

       [[  6,  70],
        [  7,  80],
        [  8,  90]],

       [[  9, 100],
        [ 10, 110],
        [ 11, 120]]])

In [111]:
ee = np.stack( (a,b), -1)
ee.shape


(4, 3, 2)

## 분리
* numpy.vsplit(array, indice) : array 배열을 수평으로 분리
* numpy.hsplit(array, indice) : array 배열을 수직으로 분리
* numpy.split(array, indice, axis=0) : array 배열을 axis 축으로 분리
  * array : 분리할 배열
  * indice : 분리할 갯수 또는 인덱스
  * axis : 기준 축 번호


In [112]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [113]:
np.hsplit(a, 3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [114]:
np.hsplit(a, [3,6])

[array([0, 1, 2]), array([3, 4, 5]), array([ 6,  7,  8,  9, 10, 11])]

In [115]:
np.hsplit(a, [3,6,9])

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [116]:
np.split(a, 3, 0)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [117]:
np.split(a, [3,6,9], 0)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [118]:
b = np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [119]:
np.vsplit(b, 2)

[array([[0, 1, 2],
        [3, 4, 5]]), array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [120]:
np.split(b, 2, 0)

[array([[0, 1, 2],
        [3, 4, 5]]), array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [121]:
np.hsplit(b, [1])

[array([[0],
        [3],
        [6],
        [9]]), array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]])]

In [122]:
np.split(b, [1], 1)

[array([[0],
        [3],
        [6],
        [9]]), array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]])]

### 검색
* ret = numpy.where(condition [, t, f]) : 조건에 맞는 요소를 찾기
  * ret : 검색 조건에 맞는 요소의 인덱스 또는 변경된 값으로 채워진 배열, 튜플
  * condition : 검색에 사용할 조건식,
  * t, f : 조건에 따라 지정할 값 또는 배열, 배열의 경우 조건에 사용한 배열과 같은 shape
    * t : 조건에 맞는 값에 지정할 값이나 배열
    * f : 조건에 틀린 값에 지정할 값이나 배열
* numpy.nonzero(array) : array에서 요소중에 0(영,zero)가 아닌 요소의 인덱스들을 반환, 튜플
* numpy.all(array [, axis]) : array의 모든 요소가 True 인지 검색
  * array : 검색 대상 배열
  * axis : 검색할 기준 축, 생략하면 모든 요소 검색, 지정하면 축 갯수별로 결과 반환
* numpy.any(array [, axis]) : array의 어느 요소이든 True가 있는지 검색


In [123]:
a = np.arange(10, 20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [124]:
np.where(a > 15)

(array([6, 7, 8, 9]),)

* 조건을 만족하면 1, 아니면 0을 지정

In [125]:
np.where(a > 15, 1, 0)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1])

In [126]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

* 조건을 만족하지 않는 것을 그대로 유지하는 방법

In [128]:
np.where(a>15, 99, a)

array([10, 11, 12, 13, 14, 15, 99, 99, 99, 99])

In [129]:
np.where(a>15, a, 0)

array([ 0,  0,  0,  0,  0,  0, 16, 17, 18, 19])

In [130]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

* 2차원인 경우 index는 각 축에 따라 생성된다.

In [131]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [132]:
coords = np.where(b>6)
coords

(array([1, 2, 2, 2, 2]), array([3, 0, 1, 2, 3]))

* 축에 따라 생성된 인덱스를 좌표 꼴로 만드는 방법

In [133]:
np.stack( (coords[0], coords[1]), -1)

array([[1, 3],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3]])

In [134]:
z = np.array([0,1,2,0,1,2])
np.nonzero(z)

(array([1, 2, 4, 5]),)

In [135]:
zz = np.array([[0,1,2], [1,2,0], [2,0,1]])
zz

array([[0, 1, 2],
       [1, 2, 0],
       [2, 0, 1]])

In [136]:
coords = np.nonzero(zz)
coords

(array([0, 0, 1, 1, 2, 2]), array([1, 2, 0, 1, 0, 2]))

In [137]:
np.stack( (coords[0], coords[1]), -1)

array([[0, 1],
       [0, 2],
       [1, 0],
       [1, 1],
       [2, 0],
       [2, 2]])

* 조건식의 결과 True/False는 1, 0으로 변환되므로 nonzero()로 구분할 수 있다.

In [138]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [139]:
np.nonzero(a>15)

(array([6, 7, 8, 9]),)

In [140]:
np.where(a>15)

(array([6, 7, 8, 9]),)

In [141]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [142]:
np.nonzero(b>6)

(array([1, 2, 2, 2, 2]), array([3, 0, 1, 2, 3]))

In [143]:
np.where(b>6)


(array([1, 2, 2, 2, 2]), array([3, 0, 1, 2, 3]))

In [144]:
t = np.array([True, True, True])

In [145]:
np.all(t)

True

In [146]:
t[1] = False
t

array([ True, False,  True])

In [147]:
np.all(t)


False

In [148]:
tt = np.array([[True, True], [False, True], [True, True]])
tt

array([[ True,  True],
       [False,  True],
       [ True,  True]])

In [149]:
np.all(tt, 0)

array([False,  True])

In [150]:
np.all(tt, 1)

array([ True, False,  True])

In [151]:
a = np.arange(10)
b = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [152]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [153]:
a==b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [154]:
np.all(a==b)

True

In [155]:
b[5] = -1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [156]:
b

array([ 0,  1,  2,  3,  4, -1,  6,  7,  8,  9])

In [157]:
np.all(a==b)

False

In [158]:
np.where(a==b)

(array([0, 1, 2, 3, 4, 6, 7, 8, 9]),)

In [159]:
np.where(a!=b)

(array([5]),)

### 기초 통계 함수
* numpy.sum(array [, axis]) : 배열의 합계 계산
* numpy.mean(array [, axis]) : 배열의 평균 계산
* numpy.amin(array [, axis])  : 배열의 최소 값 계산
* numpy.min(array [, axis]) : numpy.amin()과 동일
* numpy.amax(array [, axis]) : 배열의 최대 값 계산
* numpy.max(array [, axis]) : numpy.amax()와 동일
  * array : 계산의 대상 배열
  * axis : 계산 기준 축, 생략하면 모든 요소를 대상


In [160]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [161]:
np.sum(a)

66

In [162]:
np.sum(a, 0)

array([12, 15, 18, 21])

In [163]:
np.sum(a, 1)

array([ 6, 22, 38])

In [164]:
np.mean(a)

5.5

In [165]:
np.mean(a, 0)

array([4., 5., 6., 7.])

In [166]:
np.mean(a, 1)

array([1.5, 5.5, 9.5])

In [167]:
np.amin(a)

0

In [168]:
np.amin(a, 0)

array([0, 1, 2, 3])

In [169]:
np.amin(a, 1)

array([0, 4, 8])

In [170]:
np.amax(a)

11

In [171]:
np.amax(a, 0)

array([ 8,  9, 10, 11])

In [172]:
np.amax(a, 1)

array([ 3,  7, 11])

In [173]:
np.amin is np.min

True

In [174]:
np.max is np.amax

True