# NumPy
* http://www.numpy.org/
* https://docs.scipy.org/doc/numpy/genindex.html
* Fundamental package for scientific computing with Python
    * 강력한 N-차 배열 객체
    * 정교한 Broadcasting 함수
    * C/C++, Fortran 통합 도구
    * 유용한 선형대수, 푸리에 변환, 난수발생 기능
    * import numpy as np
![](https://i.imgur.com/u0ZWQSs.jpg)

## 모듈 Import
* np alias

In [1]:
import numpy as np
np.__version__

'1.16.2'

## 배열 생성
* 값으로 생성
    * array()
* 크기와 초기 값으로 생성
    * empty(), zeros(), ones(), full()
* 시퀀스와 난수로 생성
    * arange(), linspace(), random.randn()
* 기존 배열로 생성
    * empty_like(), zeros_like(), ones_like(), full_like()

## 값으로 생성
* ndarray 생성하는 가장 간단한 방법
* `np.array(list [, dtyle])` : : 지정한 값들로 NumPy 배열 생성
    * list : 배열 생성에 사용할 값을 갖는 파이썬 리스트 객체
    * dtype : 데이타 타입, 생략하면 값에 의해 자동 결정
        * int8, int16, int32, int64 : 부호 있는 정수
        * uint8, uint16, uint32, uint64 : 부호 없는 정수
        * float16, float32, float64, float128 : 부동 소수점을 갖는 실수
        * complex64, complex128, complex256 : 허수부를 갖는 복소수
        * bool : 불리언
* 전달한 값에 따라 dtype 결정
* 명시적 dtype 지정

### 값으로 생성 예시

In [2]:
a = np.array([1,2,3,4])
b = np.array([[1,2,3,4], [5,6,7,8]])
c = np.array([1,2,3.14,4])
d = np.array([1,2,3,4], dtype=np.float32)
print(a, a.dtype, a.shape)
print(b, b.dtype, b.shape)
print(c, c.dtype, c.shape)
print(d, d.dtype, d.shape)

[1 2 3 4] int32 (4,)
[[1 2 3 4]
 [5 6 7 8]] int32 (2, 4)
[1.   2.   3.14 4.  ] float64 (4,)
[1. 2. 3. 4.] float32 (4,)


## ndarray 속성
* ndim : 차원(축)의 수
* shape : 각 차원의 크기, 튜플
* size : 전체 요소의 갯수
* dtype : 요소의 데이타 타입
* itemsize : 각 요소의 바이트 크기

In [3]:
print(a.ndim, a.shape, a.size, a.dtype, a.itemsize)
print(b.ndim, b.shape, b.size, b.dtype, b.itemsize)
print(c.ndim, c.shape, c.size, c.dtype, c.itemsize)
print(d.ndim, d.shape, d.size, d.dtype, d.itemsize)

1 (4,) 4 int32 4
2 (2, 4) 8 int32 4
1 (4,) 4 float64 8
1 (4,) 4 float32 4


## 크기와 초기 값으로 생성
* np.empty ( tuple [, dtype])
    * 모든 요소가 초기화 되지 않은 , tuple 크기
    * np.empty( (2,3))
    * np.empty( (2,3), dtype=np.int16)
* np.zeros( tuple [, dtype])
    * 모든 요소가 0이고 tuple 크기
    * np.zeros( (3,4))
    * np.zeros( (2,3,4) , dtype=np.int16)
* np.ones ( tuple [, dtype])
    * 모든 요소가 1이고, tuple 크기
    * np.ones( (3,4) )
    * np.ones( (2,3,4) , dtype=np.int16)
* np.full(shape, fill_value [, dtype])
    * fill_value로 초기화된 배열 생성

### 크기와 초기 값으로 생성 예제

In [4]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
print(a.shape, a.ndim, a.size, a.dtype)

(2, 3) 2 6 float64


In [6]:
b = np.zeros((2,3,4), dtype=np.uint8)
b

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=uint8)

In [7]:
c = np.ones((2,3), dtype=np.float32)
c

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [8]:
d = np.empty((2,3))
d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
e = np.empty((2,3), dtype=np.float32)
e

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [10]:
f = np.full((2,3),255)
f

array([[255, 255, 255],
       [255, 255, 255]])

## Sequence로 생성
* numpy.arange([start=0, ] stop [, step=1, dtype=float64])
    * start 값과 stop 값 사이에 step 간격으로 생성(갯수 보다 간격이 중요한 경우)
    * start : 시작 값
    * stop : 종료 값, 범위에 포함하는 수는 stop-1 까지
    * step : 증가 값
    * dtype : 데이타 타입
* numpy.linspace(start, stop, num)
    * start와 stop 값 사이에 num 갯수 만큼 생성(간격 보다 갯수가 중요한 경우)
    * start : 시작 값
    * stop : 종료 값
    * num : 생성할 값의 갯수


### Sequence로 생성 예시

In [11]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [12]:
b = np.arange(5.0)
b

array([0., 1., 2., 3., 4.])

In [13]:
c = np.arange(3,9, 2)
c

array([3, 5, 7])

In [14]:
d = np.linspace(1,10, 5)
d

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

## 난수로 생성
* numpy.random.rand([d0 [, d1 [..., dn]]]) :
    * d0, d1..dn : shape, 생략하면 난수 한개 반환
    * 0과 1 사이의 무작위 수
* numpy.random.randn([d0 [, d1 [..., dn]]]) :
    * 평균=0, 분산=1, 표준정규 분포를 따르는 무작위 수

### 난수로 생성 예시

In [15]:
e = np.random.rand()
e

0.29147742098369245

In [16]:

f = np.random.randn()
f

1.5046216859836923

In [17]:
g = np.random.randn(2,3)
g

array([[-1.56678752, -0.71665862,  1.50701624],
       [-0.4278727 ,  1.56800434, -0.30439938]])

In [18]:
h = np.random.randn(2,3)
h

array([[-1.45734142, -1.1261647 , -0.44059225],
       [ 1.79853717, -1.64419533,  1.2571734 ]])

## 기존 배열로 생성
* np.empty_like(array [, dtype] ) 
    * array와 같은 shape과 dtype의 초기화 되지 않은 배열 생성
* zeros_like(array [, dtype]) 
    *  0(영, zero)로 초기화된 array와 같은 shape과 dtype의 배열 생성
* ones_like(array [, dtype]) 
    * 1로 초기화된 array와 같은 shape과 dtype의 배열 생성
* full_like(array, fill_value [, dtype]) 
    * fill_value로 초기화된 array와 같은 shape과 dtype의 배열 생성

### 기존 배열로 생성 예시

In [19]:
aa = np.empty_like(a)
aa

array([1338434528,        376,          0,          0,          1])

In [20]:
bb = np.zeros_like(b)
bb

array([0., 0., 0., 0., 0.])

In [21]:
cc = np.ones_like(c)
cc

array([1, 1, 1])

In [22]:
dd = np.full_like(d, 125)
dd

array([125., 125., 125., 125., 125.])

## dtype 변경
* ndarray.astype(dtype)
  * dtype : 변경하고 싶은 dtype, 문자열 또는 dtype
* numpy.uint*XX* (array): array를 부호 없는 정수(uint) 타입으로 변경해서 반환
  * uint*XX* : uint8, unit16, uint32, uint64
* numpy.int*XX*(array): array를 int 타입으로 변경해서 반환
  * int*XX* : int8, int16, int32, int64
* numpy.float*XX*(array) : array를 float 타입으로 변경해서 반환
  * float*XX* : float16, float32, float32, float64, float128
* numpy.complex*XX*(array) : array를 복소수(complex) 타입으로 변경해서 반환
  * complex*XX* : complex64, complex128, complex256


In [23]:
a = np.arange(10)
b = a.astype('float32')
a, b

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32))

In [24]:
c = np.uint8(b)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [25]:
d = c.astype(np.float32)
d

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

## shape 변경
* numpy.reshape(ndarray, newshape)
* ndarray.reshape(newshape)
  * ndarray : 원본 배열 객체
  * newshape : 변경하고자 하는 새로운 shape, 튜블
  * -1 : 해당 컬럼은 크기 미지정
* numpy.ravel(ndarray)
  * 1차원 배열로 변경
* ndarray.T : 전치배열(Transpose)
    * numpy.transpose(ndarray)

### shape변경 예시

In [26]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [27]:
b = a.reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [28]:
c = np.reshape(a, (2,3))
c

array([[0, 1, 2],
       [3, 4, 5]])

### -1은 알아서 계산하라는 의미

In [29]:
d = np.arange(100).reshape(2, -1)
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [30]:
d.shape

(2, 50)

In [31]:
e = np.arange(100).reshape(-1, 5)
e

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [32]:
e.shape

(20, 5)

### 1차원으로 변경하는 3가지 방법
* reshape(n)
* reshape(-1)
* ravel()

In [33]:
f = np.zeros((2,3))
f

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
f.reshape((6,))

array([0., 0., 0., 0., 0., 0.])

In [35]:
f.reshape(-1)

array([0., 0., 0., 0., 0., 0.])

In [36]:
np.ravel(f)

array([0., 0., 0., 0., 0., 0.])

### 전치 행렬 T(Transpose)

In [37]:
g = np.arange(10).reshape(2,-1)
g

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [38]:
g.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [39]:
np.transpose(g)

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

## 배열 연산
* 장점 : 반복문 회피
    * 수식 간소화, 속도 향상
* Vetorizing
    * 크기가 같은 배열간의 연산
    * 두 배열의 같은 자리의 요소간의 연산
* Broadcating
    * 스케일러(scalar, 스칼라)와 배열간 연산
    * 크기가 다른 배열간 연산

### list, Python built-in 
* Loop 사용 필수
    * 파이썬 리스트의 각 항목을 1씩 증가시키려면 아래 처럼 loop 를 사용해야 한다.

In [40]:
mylist = list(range(10))
mylist

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [41]:
for i in range(len(mylist)):
     mylist[i] = mylist[i] + 1
mylist

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

### NumPy Vectorizing
    * 크기가 같은 배열간의 연산
    * 두 배열의 같은 자리 요소간의 연산

In [42]:
a = np.arange(10, 60, 10)
b = np.arange(1, 6)

In [43]:
a

array([10, 20, 30, 40, 50])

In [44]:
b

array([1, 2, 3, 4, 5])

In [45]:
a + b

array([11, 22, 33, 44, 55])

In [46]:
a - b

array([ 9, 18, 27, 36, 45])

In [47]:
a * b

array([ 10,  40,  90, 160, 250])

In [48]:
a / b

array([10., 10., 10., 10., 10.])

In [49]:
a ** b

array([       10,       400,     27000,   2560000, 312500000], dtype=int32)

### 비교 연산
* 산술연산 뿐만 아니라 비교 연산도 가능

In [50]:
a

array([10, 20, 30, 40, 50])

In [51]:
a > 2

array([ True,  True,  True,  True,  True])

### Scalar와 배열간의 Broadcasting 연산
* 스케일러(scalar, 스칼라)와 배열의 모든 요소간 연산

In [52]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
a + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [55]:
a + 5

array([5, 6, 7, 8, 9])

In [56]:
a - 2

array([-2, -1,  0,  1,  2])

In [57]:
a * 2

array([0, 2, 4, 6, 8])

In [58]:
a / 2

array([0. , 0.5, 1. , 1.5, 2. ])

In [59]:
a ** 2

array([ 0,  1,  4,  9, 16], dtype=int32)

In [60]:
b = np.arange(6).reshape(2, -1)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [61]:
b * 2

array([[ 0,  2,  4],
       [ 6,  8, 10]])

### Shape 오류
* 배열간의 연산에서 두 배열의 shape이 일치하지 않으면 에러 발생

In [62]:
a = np.ones((2,3))
b = np.ones((3,2))
a + b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

### 크기가 다른 배열간의  Broadcasting 연산
* shape이 달라도 연산 가능
* 차원이 다른 배열인 경우 작은 차원 배열을 큰 차원의 낮은 차원을 확장
* 차원이 같은 배열인 경우 축이 1이면 확장
![broadcating](http://www.astroml.org/_images/fig_broadcast_visual_1.png)

#### 차원이 다른 배열의 Broadcasting 예시

In [70]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [71]:
c = np.arange(3)
c

array([0, 1, 2])

In [87]:
f'a: {a.shape}, c:{c.shape}'

'a: (3, 1, 4), c:(3,)'

In [74]:
a + c

array([[1., 2., 3.],
       [1., 2., 3.]])

#### 축이 1인 배열의 Broadcasting 예시

In [75]:
d = np.arange(2).reshape(2,1)
a.shape, d.shape

((2, 3), (2, 1))

In [76]:
a + d

array([[1., 1., 1.],
       [2., 2., 2.]])

#### 차원이 다르고 축이 1인 배열의  Broadcasting 예시

In [79]:
a = np.arange(3).reshape(3,1)
b = np.arange(3)
f'a.shape:{a.shape}, b.shape:{b.shape}'

'a.shape:(3, 1), b.shape:(3,)'

In [80]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [90]:
a = np.arange(12).reshape(3,1,4)
b = np.arange(12).reshape(3,4)
f'a:{a.shape}, b:{b.shape}'

'a:(3, 1, 4), b:(3, 4)'

In [86]:
a + b

array([[[ 0,  2,  4,  6],
        [ 4,  6,  8, 10]],

       [[12, 14, 16, 18],
        [16, 18, 20, 22]],

       [[24, 26, 28, 30],
        [28, 30, 32, 34]]])

## Matrix Operation(행렬  연산)
* np.matmul(a, b) : 행렬 곱
* np.dot(a, b) : 벡터의 내적
    * 2차원인 경우 `np.matmul()`과 동일

In [91]:
a = np.array([[1],
               [2]])
b = np.array([[4, 1]])
c1 = np.matmul(a, b)
c2 = np.dot(a, b)
print(c1)
print(c2)

[[4 1]
 [8 2]]
[[4 1]
 [8 2]]


## Indexing(인덱싱)과 Slicing(슬라이싱)
* 1차원
    * a[0] : 특정 요소
    * a[1 : 5] : 1~4번째 요소
    * a[5: ] : 5번째부터 끝까지
    * a[:5] : 처음 부터 4번째 까지
    * a[ : ] : 모든 요소
* 2차원
    * a[2, 3 ] : 2행 3열 요소
    * a[2:4,  3] : 2~3행의  3열 요소
    * a[ 2, 1:4] : 2행의 1~3열 요소
    * a[2, :] : 2행의 모든 열 요소
    * a[:, 2] : 모든 행의 2열 요소
    * a[1:3, : ] : 1~2행의 모든 열 

### 인덱싱과 슬라이싱 예시
* 하나의 엘레먼트에 접근하려 할때 해당 인덱스로 접근

In [92]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
a[5]

5

### 인덱스가 모자란 경우
* n 차원의 경우 n개의 인덱스가 주어지지 않으면 해당 축 전체 요소 반환

In [94]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [95]:
b[1]

array([4, 5, 6, 7])

In [96]:
b[1,2]

6

In [97]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
a[5] = 9
a

array([0, 1, 2, 3, 4, 9, 6, 7, 8, 9])

In [99]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [100]:
b[0] = 0
b

array([[ 0,  0,  0,  0],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [101]:
b[1,2] = 99
b


array([[ 0,  0,  0,  0],
       [ 4,  5, 99,  7],
       [ 8,  9, 10, 11]])

In [102]:
a = np.arange(10);
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
a[2:5]

array([2, 3, 4])

In [104]:
a[5:]

array([5, 6, 7, 8, 9])

In [105]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [107]:
b[0:2, 1]

array([1, 5])

In [108]:
b[0:2, 1:3]

array([[1, 2],
       [5, 6]])

In [109]:
b[2, : ]

array([ 8,  9, 10, 11])

In [110]:
b[:, 1]

array([1, 5, 9])

In [111]:
b[0:2, 1:3] = 0
b

array([[ 0,  0,  0,  3],
       [ 4,  0,  0,  7],
       [ 8,  9, 10, 11]])

In [112]:
bb = b[0:2, 1:3]
bb

array([[0, 0],
       [0, 0]])

In [113]:
bb[0] = 99       
b

array([[ 0, 99, 99,  3],
       [ 4,  0,  0,  7],
       [ 8,  9, 10, 11]])

## Bool Indexing 과 Fancy Indexing
* 배열 요소를 불규칙적으로 선택하는 방법
* Bool indexing : 선택하려는 요소만 True인 배열로 선택
    * Bool type (True/False)
    * a[a > 4]
    * a[a > 4] = 0
    * 조건 연산:  > , >=, <, <=, ==, !=
* Fancy Indexing : 선택하려는 요소의 인덱스의 배열로 선택
    * 조건을 만족하는 데이타만 추출하거나 초기화
    * 색인 배열
        * a[[0,2,4]]
        * b = [1,2,3]
        * a[b]

### Bool/Fancy indexing 예시

In [114]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [115]:
a[[True, False, True, False, True]]

array([0, 2, 4])

In [116]:
a[[1,3]]

array([1, 3])

#### 조건식과 Bool indexing
* 조건식을 직접 인덱스에 넣어도 가능하다

In [118]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
b = a > 5
b

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [120]:
a[b]

array([6, 7, 8, 9])

In [121]:
a[a>5]

array([6, 7, 8, 9])

In [122]:
a[a>5] =1
a

array([0, 1, 2, 3, 4, 5, 1, 1, 1, 1])

In [123]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [124]:
b[[0,2]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [125]:
b[[0,2], [2,3]]

array([ 2, 11])

## Stack, Concatenate(붙이기)
* numpy.hstack(arrays) : arrays 배열을 수평으로 병합
* numpy.vstack(arrays) : arrays 배열을 수직으로 병합
* numpy.concatenate(arrays, axis=0) :  arrays 배열을 지정한 축 기준으로 병합
* numpy.stack( arrays, axis=0) : arrays 배열을 새로운 축으로 병합
  * arrays : 병합 대상 배열, 튜플


In [126]:
a = np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [127]:
b = np.arange(10, 14).reshape(2,2)
b

array([[10, 11],
       [12, 13]])

In [128]:
np.vstack( (a,b) )

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13]])

In [129]:
np.hstack( (a,b) )

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13]])

### concatenate 축 번호
* 축번호를 지정하는 것이 중요하다.

In [130]:
np.concatenate((a,b), 0)

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13]])

In [133]:
np.concatenate((a,b), 1)

array([[  0,   1,   2,  10,  20,  30],
       [  3,   4,   5,  40,  50,  60],
       [  6,   7,   8,  70,  80,  90],
       [  9,  10,  11, 100, 110, 120]])

In [134]:
a = np.arange(12).reshape(4,3)
b = np.arange(10, 130, 10).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [135]:
b

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

### Stack()
* stack()은 지정한 축번호가 새로 추가된다.

In [136]:
c = np.stack( (a,b), 0)
c.shape

(2, 4, 3)

In [137]:
c

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90],
        [100, 110, 120]]])

In [ ]:
d = np.stack( (a,b), 1)
d.shape

In [138]:
d

array([[0],
       [1]])

In [139]:
e = np.stack( (a,b), 2)
e.shape

(4, 3, 2)

In [140]:
e

array([[[  0,  10],
        [  1,  20],
        [  2,  30]],

       [[  3,  40],
        [  4,  50],
        [  5,  60]],

       [[  6,  70],
        [  7,  80],
        [  8,  90]],

       [[  9, 100],
        [ 10, 110],
        [ 11, 120]]])

In [141]:
ee = np.stack( (a,b), -1)
ee.shape


(4, 3, 2)

## Split(분리)
* numpy.vsplit(array, indice) : array 배열을 수평으로 분리
* numpy.hsplit(array, indice) : array 배열을 수직으로 분리
* numpy.split(array, indice, axis=0) : array 배열을 axis 축으로 분리
  * array : 분리할 배열
  * indice : 분리할 갯수 또는 인덱스
  * axis : 기준 축 번호


In [142]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [143]:
np.hsplit(a, 3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [144]:
np.hsplit(a, [3,6])

[array([0, 1, 2]), array([3, 4, 5]), array([ 6,  7,  8,  9, 10, 11])]

In [145]:
np.hsplit(a, [3,6,9])

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [146]:
np.split(a, 3, 0)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [147]:
np.split(a, [3,6,9], 0)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [148]:
b = np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [149]:
np.vsplit(b, 2)

[array([[0, 1, 2],
        [3, 4, 5]]), array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [150]:
np.split(b, 2, 0)

[array([[0, 1, 2],
        [3, 4, 5]]), array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [151]:
np.hsplit(b, [1])

[array([[0],
        [3],
        [6],
        [9]]), array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]])]

In [152]:
np.split(b, [1], 1)

[array([[0],
        [3],
        [6],
        [9]]), array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]])]

## Search(검색)
* ret = numpy.where(condition [, t, f]) : 조건에 맞는 요소를 찾기
  * ret : 검색 조건에 맞는 요소의 인덱스 또는 변경된 값으로 채워진 배열, 튜플
  * condition : 검색에 사용할 조건식,
  * t, f : 조건에 따라 지정할 값 또는 배열, 배열의 경우 조건에 사용한 배열과 같은 shape
    * t : 조건에 맞는 값에 지정할 값이나 배열
    * f : 조건에 틀린 값에 지정할 값이나 배열
* numpy.nonzero(array) : array에서 요소중에 0(영,zero)가 아닌 요소의 인덱스들을 반환, 튜플
* numpy.all(array [, axis]) : array의 모든 요소가 True 인지 검색
  * array : 검색 대상 배열
  * axis : 검색할 기준 축, 생략하면 모든 요소 검색, 지정하면 축 갯수별로 결과 반환
* numpy.any(array [, axis]) : array의 어느 요소이든 True가 있는지 검색


In [153]:
a = np.arange(10, 20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [154]:
np.where(a > 15)

(array([6, 7, 8, 9], dtype=int64),)

### where, 조건 결과로 채우기
* 조건을 만족하면 1, 아니면 0을 지정

In [155]:
np.where(a > 15, 1, 0)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1])

In [156]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

### where, 값 유지
* 조건을 만족하지 않는 것을 그대로 유지하는 방법

In [157]:
np.where(a>15, 99, a)

array([10, 11, 12, 13, 14, 15, 99, 99, 99, 99])

In [158]:
np.where(a>15, a, 0)

array([ 0,  0,  0,  0,  0,  0, 16, 17, 18, 19])

In [159]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

### where,  다차원 인덱스
* 검색 대상 배열이 2차원이상인 경우 index는 각 축에 따라 생성

In [162]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [163]:
coords = np.where(b>6)
coords

(array([1, 2, 2, 2, 2], dtype=int64), array([3, 0, 1, 2, 3], dtype=int64))

### where, 다차원 인덱스를 좌표로 만들기
* 축에 따라 생성된 인덱스를 좌표 꼴로 만드는 방법

In [164]:
np.stack( (coords[0], coords[1]), -1)

array([[1, 3],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3]], dtype=int64)

In [165]:
z = np.array([0,1,2,0,1,2])
np.nonzero(z)

(array([1, 2, 4, 5], dtype=int64),)

In [166]:
zz = np.array([[0,1,2], [1,2,0], [2,0,1]])
zz

array([[0, 1, 2],
       [1, 2, 0],
       [2, 0, 1]])

In [167]:
coords = np.nonzero(zz)
coords

(array([0, 0, 1, 1, 2, 2], dtype=int64),
 array([1, 2, 0, 1, 0, 2], dtype=int64))

In [168]:
np.stack( (coords[0], coords[1]), -1)

array([[0, 1],
       [0, 2],
       [1, 0],
       [1, 1],
       [2, 0],
       [2, 2]], dtype=int64)

### 조건식과 nonzero()
* 조건식의 결과 True/False는 1, 0으로 변환되므로 nonzero()로 구분 가능

In [169]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [170]:
np.nonzero(a>15)

(array([6, 7, 8, 9], dtype=int64),)

In [171]:
np.where(a>15)

(array([6, 7, 8, 9], dtype=int64),)

In [172]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [173]:
np.nonzero(b>6)

(array([1, 2, 2, 2, 2], dtype=int64), array([3, 0, 1, 2, 3], dtype=int64))

In [174]:
np.where(b>6)


(array([1, 2, 2, 2, 2], dtype=int64), array([3, 0, 1, 2, 3], dtype=int64))

In [175]:
t = np.array([True, True, True])

In [176]:
np.all(t)

True

In [177]:
t[1] = False
t

array([ True, False,  True])

In [178]:
np.all(t)


False

In [179]:
tt = np.array([[True, True], [False, True], [True, True]])
tt

array([[ True,  True],
       [False,  True],
       [ True,  True]])

In [180]:
np.all(tt, 0)

array([False,  True])

In [181]:
np.all(tt, 1)

array([ True, False,  True])

In [182]:
a = np.arange(10)
b = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [183]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [184]:
a==b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [185]:
np.all(a==b)

True

In [186]:
b[5] = -1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [187]:
b

array([ 0,  1,  2,  3,  4, -1,  6,  7,  8,  9])

In [188]:
np.all(a==b)

False

In [189]:
np.where(a==b)

(array([0, 1, 2, 3, 4, 6, 7, 8, 9], dtype=int64),)

In [190]:
np.where(a!=b)

(array([5], dtype=int64),)

## Basic Statistic Function(기초 통계 함수)
* numpy.sum(array [, axis]) : 배열의 합계 계산
* numpy.mean(array [, axis]) : 배열의 평균 계산
* numpy.amin(array [, axis])  : 배열의 최소 값 계산
* numpy.min(array [, axis]) : numpy.amin()과 동일
* numpy.amax(array [, axis]) : 배열의 최대 값 계산
* numpy.max(array [, axis]) : numpy.amax()와 동일
  * array : 계산의 대상 배열
  * axis : 계산 기준 축, 생략하면 모든 요소를 대상
* numpy.std(array [, axis]) : 표준 편차


In [191]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [192]:
np.sum(a)

66

In [193]:
np.sum(a, 0)

array([12, 15, 18, 21])

In [194]:
np.sum(a, 1)

array([ 6, 22, 38])

In [195]:
np.mean(a)

5.5

In [196]:
np.mean(a, 0)

array([4., 5., 6., 7.])

In [197]:
np.mean(a, 1)

array([1.5, 5.5, 9.5])

In [198]:
np.amin(a)

0

In [199]:
np.amin(a, 0)

array([0, 1, 2, 3])

In [200]:
np.amin(a, 1)

array([0, 4, 8])

In [201]:
np.amax(a)

11

In [202]:
np.amax(a, 0)

array([ 8,  9, 10, 11])

In [203]:
np.amax(a, 1)

array([ 3,  7, 11])

In [204]:
np.amin is np.min

True

In [205]:
np.max is np.amax

True

In [206]:
np.std(a)

3.452052529534663

In [207]:
np.std(a, 0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [208]:
np.std(a, 1)

array([1.11803399, 1.11803399, 1.11803399])

## Mathmatic Function(수학 함수)
* `np.sqrt(x)` : 제곱근
* `np.log(x)` : 로그 함수
* `np.exp(x)` : 지수 함수
* `np.abs(x)` : 절대값
* `np.round(x)`: 반올림
* `np.ceil(x)` : 올림
* `np.floor(x)` : 버림

In [209]:
np.sqrt(4)

2.0

In [210]:
np.log(10)

2.302585092994046

In [211]:
np.exp(2)

7.38905609893065

In [212]:
np.log(np.exp(2))

2.0

In [213]:
np.abs(2-10)

8

In [214]:
np.round(1.4)

1.0

In [215]:
np.round(1.6)

2.0

In [216]:
np.ceil(1.4)

2.0

In [217]:
np.floor(1.9)

1.0

## File I/O(파일 입출력)
* `np.save('file_name.npy', array [, array-n...])`
* `np.savez('file_name.npz', name=array [, name-n=array-n...])`
* `data = np.load('file_name')`


In [218]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [219]:
np.save('data.npy', data)
data = None
print(data)

None


In [220]:
data = np.load('data.npy')
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [221]:
data1 = np.arange(10)
data2 = np.arange(10,20)
np.savez('datas.npz', data1=data1, data2=data2)

In [222]:
loaded = np.load('datas.npz')
loaded.files

['data1', 'data2']

In [223]:
loaded['data1']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [224]:
loaded['data2']

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])