# Desition Tree & Ensemble

## Decision Tree
* 의사결정 나무
    * 트리구조 분류 알고리즘
* 스무고개 놀이와 비슷
    * 예/아니오 질문을 이어 나가면서 학습
![image.png](https://i.imgur.com/q16hdP5.png)

### 노드 선택 규칙
* ID3 알고리즘
    * 엔트로피(entropy)
    * 분자의 무질서함 측정, 열역학(양자역학, 정보이론, 통계역학 등)
    * 엔트로피가 크면 불확실성이 크다
    * 엔트로피 대신 지니 불순도 대체 가능
* $\displaystyle E(x) = -\sum_{i=1}^n p(x_i)log_b(p(x_i)) = -p(Pos)log2(p(Pos)) - p(Neg)log2(p(Neg))$

![image.png](https://i.imgur.com/1rP82Kk.png)

### 노드 선택 규칙
* ID3 알고리즘
    * Information Gain(정보 획득량)
        * $IG(T,a) = E(T) - E(T,a)$
        * 분리전 엔트로피에서 분리 후 엔트로피를 빼기 연산
            * 양수 : 엔트로피가 작아 졌다
        * 분리전, 후의 엔트로피가 작아지는 노드 선택
        * 처리할 수 있는 데이타 수가 가장 많은 노드
    * 선택 갯수
        * 모든 특성이 경로에 포함 되있는 경우
        * 엔트로피가 0인 경로가 나온 경우



### 노드 선택 규칙
* CART(Classification And Regression Tree)알고리즘
    * 말단 노드를 제외한 모든 노드는 자식을 2개로 제약
    * 하나의 특성 k의 임계값 T를 정해서 두개의 서브셋으로 나눔
    * 불순도가 가장 낮은 k와 T를 선정
    * $\displaystyle J(k, t_k) = \frac{m_{left}}{m}G_{left} + \frac{m_{right}}{m}G_{right}$
        * $G_{left/right}$ : 왼쪽 또는 오른족 서브셋의 불순도
        * $m_{left/right}$ : 왼쪽 또는 오른족 서브셋의 샘플수
    * Gini 불순도(impurity), 노드의 샘플이 같은 클래스에 속한 정도
        * $G_i = 1 - \sum_{k=1}^n P_i, k^2 $
            * ex) sample= 54, value = [0,49,5] , gini=0.168
            * $1-(0/54)^2 - (49/54)2 - (5/54)^2 \approx 0.168$
        


### 장단점
* 장점
    * 상대적으로 빠름
    * 데이타의 전처리가 거의 불필요
        * 예: 스케일링, 정규화, 표준화
    * 결정 트리는 Overfitting(과적합)이 되지 않는다.
        * 앙상블(Ensemble) 기법에 좋다.
        * Random Forest
        * Gradient Boosting
    * White Box Model
        * 결정 방식(예측의 근거) 명확
        * Neural Network와 상반 - Black Box Model
* 단점
    * 연속적 특성 데이타에 부적합
    * 클래스가 많고 데이타가 적을 때 나쁜 성능
    * 훈련 과정의 계산량이 많다.


### scikit-learn
* `sklearn.tree.DecisionTreeClassifier`
    * `criterion` : {'gini' , 'entropy'}
        * `gini` : default
    * ```
tree_clf = DecisionTreeClassifier()
tree_clf.fit(X,y)
```
* 이진 트리 CART 알고리즘 사용
    * leaf node 외 모든 노드의 자식노드는 2개로 제한
* 노드 속성
    * samples : 노드에 속한 샘플 수 
    * value : 각 클래스에 속한 샘플 수 
* export_graphviz() 함수로 시각화 파일 생성


### 모듈 설치
* pydot
    * pip install pydot
* grphviz
    * 실행파일 설치 : https://graphviz.gitlab.io/download/
    * windows : https://graphviz.gitlab.io/_pages/Download/Download_windows.html
    * pip install graphviz

In [4]:
!pip install pydot graphviz

You should consider upgrading via the 'python -m pip install --upgrade pip' command.


### Decision Tree 예제
몸매, 얼굴, 결혼 여부로 사귀고 싶은 사람을 분류하는 예제

*  dataset

몸매 | 얼굴 | 미혼| 이상형
---|---|---|---
yes | yes | yes| yes
yes | yes | no| no
no | no | yes | no
no| yes|yes | no
yes|yes|no|no
yes |no|yes| no
no|no|yes|no
no| yes| no| no

### 알고리즘
* ID3 Root Node
    * 클래스 이상형의 엔트로피 :$ E(이상형)= E(1^+, 7^-) = -\frac{1}{8}log2(\frac{1}{8}) - \frac{7}{8}log2(\frac{7}{8}) \approx 0.543$
        * $IG(이상형, 몸매) = E(이상형) - E(이상형, 몸매) = 0.543 - \frac{4}{8} E(1^+,3^-) + \frac{4}{8} E(0^+, 4^-) = 0.138  $
        * $IG(이상형, 얼굴) = E(이상형) - E(이상형, 얼굴) = 0.543 - \frac{5}{8} E(1^+,4^-) + \frac{3}{8} E(0^+, 3^-) = 0.093  $
        * $IG(이상형, 미혼) = E(이상형) - E(이상형, 미혼) = 0.543 - \frac{4}{8} E(1^+,4^-) + \frac{3}{8} E(0^+, 3^-) = 0.093  $
    * 몸매를 root node로 선정
    
* CART Root Node
    * $J(몸매, 0.5) = \frac{4}{8}G(4,0) + \frac{4}{8}G(3,1) = 0 + \frac{4}{8}(1- \frac{3}{4}^2 - \frac{1}{4}^2) = 0.1875 $ 선정
    * $J(얼굴, 0.5) = \frac{5}{8}G(4,1) + \frac{3}{8}G(3,0) = \frac{5}{8}(1- \frac{4}{5}^2 - \frac{1}{5}^2)  + 0= 0.1993 $
    * $J(미혼, 0.5) = \frac{5}{8}G(4,1) + \frac{3}{8}G(3,0) = \frac{5}{8}(1- \frac{4}{5}^2 - \frac{1}{5}^2)  + 0= 0.1993 $
    

#### 결정 트리 이상형 예제(entropy)

In [5]:
import numpy as np
import matplotlib.pylab as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
from sklearn.externals.six import StringIO  
import pydot
#from IPython import display
import graphviz

In [7]:
data = np.array([[1,1,1,1],
                 [1,1,0,0],
                 [0,0,1,0],
                 [0,1,1,0],
                 [1,1,0,0],
                 [1,0,1,0],
                 [0,0,1,0],
                 [0,1,0,0]])

X = data[:, :-1]
y = data[:, -1]
print(X, y)

tree_ent = DecisionTreeClassifier(criterion='entropy')
tree_ent.fit(X,y)
print("Train Accurray: ", tree_ent.score(X, y))
dot_data = StringIO()
export_graphviz(tree_ent,
                out_file=dot_data,
                feature_names=["몸매", "얼굴", "미혼"],
                class_names=["폭탄", "이상형"])
graph = pydot.graph_from_dot_data(dot_data.getvalue())[0]
display(graphviz.Source(graph))

print(tree_ent.predict([[1,1,1]]))
print(tree_ent.predict([[0,1,1]]))
print(tree_ent.predict([[1,0,1]]))
print(tree_ent.predict([[1,1,0]]))
print(tree_ent.predict([[0,0,0]]))

[[1 1 1]
 [1 1 0]
 [0 0 1]
 [0 1 1]
 [1 1 0]
 [1 0 1]
 [0 0 1]
 [0 1 0]] [1 0 0 0 0 0 0 0]
Train Accurray:  1.0


ExecutableNotFound: failed to execute ['dot', '-Tsvg'], make sure the Graphviz executables are on your systems' PATH

[1]
[0]
[0]
[0]
[0]


#### 결정 트리 이상형 예제( Jini)

In [ ]:
# 하드 코딩한 샘플과 sklearn으로 DT 예제 및 시각화 예제
# 사귀고 싶은 이상형 찾기
# 특성 : 몸매, 얼굴, 미혼, 이상형
data = np.array([[1,1,1,1],
                 [1,1,0,0],
                 [0,0,1,0],
                 [0,1,1,0],
                 [1,1,0,0],
                 [1,0,1,0],
                 [0,0,1,0],
                 [0,1,0,0]])

X = data[:, :-1]
y = data[:, -1]
print(X, y)

tree_jini = DecisionTreeClassifier(random_state=0)
tree_jini.fit(X,y)
print("Train Accurray: ", tree_jini.score(X, y))

'''
dot_data = StringIO()
export_graphviz(tree, out_file=dot_data)
dot_data.getvalue()

graph = pydot.graph_from_dot_data(dot_data.getvalue())
print( '"graph" is object of type {}'.format(type(graph[0])), graph[0].create_png())

display.Image(graph[0].create_png())
'''
'''
export_graphviz(tree,
                out_file="./father_tree.dot",
        feature_names=["gender", "marrage", "children"],
        class_names=["Mail", "single", "father"],
        rounded=True,
        filled=True )
with open("father_tree.dot") as f:
    dot_graph = f.read()
    display(graphviz.Source(dot_graph))
    #dot = graphviz.Source(dot_graph)
    #dot.format = 'png'
    #dot.render(filename='father_tree.png', directory='./', cleanup=True)
    #dot
'''

dot_data = StringIO()
export_graphviz(tree_jini,
                out_file=dot_data,
                feature_names=["몸매", "얼굴", "미혼"],
                class_names=["폭탄", "이상형"],)
graph = pydot.graph_from_dot_data(dot_data.getvalue())[0]
display(graphviz.Source(graph))

print(tree_jini.predict([[1,1,1]]))
print(tree_jini.predict([[0,1,1]]))
print(tree_jini.predict([[1,0,1]]))
print(tree_jini.predict([[1,1,0]]))
print(tree_jini.predict([[0,0,0]]))


#### 유방암 예제, DT

In [ ]:
def plot_feature_importance(dataset, model):
    n = len(dataset.feature_names)
    plt.barh(range(n), model.feature_importances_, align='center')
    plt.yticks(np.arange(n), dataset.feature_names)
    plt.xlabel("feature importance")
    plt.ylabel('features')
    plt.show()
    

In [ ]:
# 분류 예제 , sklearn 책의 유방암 p106
from sklearn import model_selection
from sklearn import datasets

def cancer_lab(depth=0):
    random_state = 0
    cancer = datasets.load_breast_cancer()
    X_train, X_test, y_train, y_test = model_selection.train_test_split(cancer.data,
                                                        cancer.target,
                                                        stratify=cancer.target,
                                                        random_state=42
                                                        )
    
    if depth == 0:
        tree = DecisionTreeClassifier(random_state=random_state)
    else :
        tree = DecisionTreeClassifier(random_state=random_state, max_depth=4) 
    tree.fit(X_train, y_train)
    print('Train Accuracy(depth=%d): %.3f%%'%(depth, tree.score(X_train, y_train)*100))
    print('Test Accuracy(depth=%d): %.3f%%'%(depth, tree.score(X_test, y_test)*100))

    return tree, cancer

# max_depth를 지정한 것이 훈련 정확도는 낮지만, 테스트 정확도가 높다
tree1, cancer = cancer_lab() 
print("feature importance:", tree1.feature_importances_)
tree2, cancer = cancer_lab(4)
print("feature importance:", tree1.feature_importances_)

dot_data = StringIO()
export_graphviz(tree2,
               out_file=dot_data,
               feature_names=cancer.feature_names,
               class_names=['악성', '양성'])
graph = pydot.graph_from_dot_data(dot_data.getvalue())[0]
display(graphviz.Source(graph))

plot_feature_importance(cancer, tree2)


### Ensemble(앙상블) 기법
* 여러 머신러닝 모델을 연결해서 더 강력한 모델을 만드는 기법
* 서로 같거나 다른 여러 모델을 만들어서 예측한 결과를 투표하는 기법
    * 직접 투표 : 각 모델의 예측 결과 중 많은 것을 선택
        * hard voting
    * 간접 투표 : 각 모델은 클래스 확률을 예측
        * 모든 확률을 평균내어 높은 확률을 선택
        * soft voting
![image.png](https://i.imgur.com/xmhDFgu.png)

### Ensemble(앙상블) 기법
* 대표적 앙상블 기법
    * Bagging(배깅, bootstrap aggregating)
        * 같은 훈련 알고리즘 사용
        * 훈련 데이타셋 중복(bootstraping) 허용
    * Pasting(페이스팅)
        * 같은 훈련 알고리즘 사용
        * 훈련 데이타셋 중복 불허
    * Boosting(부스팅)
        * AdaBoost(아다부스트, Adaptive Boosting)
            * 과소적합된 훈련 가중치를 더 높여서 새로운 모델 학습
        * Gradient Boost(그래디언트 부스트)
            * 랜덤 제거, 사전가지치기 사용
            * 얕은 트리(약한 학습기) 여러개 연결
            * 핵심 변수 : learning_rate
                * 이전 모델 잔여 오차 개선
    * Stacking(스태킹, Stacked generalization)
        * 여러 모델의 결과를 단순히 취합하는 것이 아니라 새로운 블렌딩 추가

### Random Forest
* 대표적 앙상블 모델
* 과대적합 해소
* 조금씩 다른 여러개의 결정 트리로 구성
* 각 결정트리는 특정 문제에 과대적합된 모델
* 생성 순서
    * 생성할 트리 갯수를 정하고 Decision Tree를 여러개 생성
    * 각 DT의 노드는 최적이 아닌 랜덤하게 생성
    * 부트스트랩 샘플 생성
        * n개의 샘플을 무작위로 여러번 추출
    * 최선의 특성이 아닌 무작위 특성 노드를 선택해서 트리 생성
    * 중복되는 데이타로 각 DT 훈련
    * 각 DT에게 예측을 시켜서 가장 많이 나온 답을 선택 : Aggregating

## scikit-learn의 ensemble 구현
* sklearn.ensemble.Votingclassifier
    * `estimator=[('lr', log_clf), ('rf', rnd_clf), ('svc', svm_clf)]`
    * `votion='hard`
* sklearn.ensemble.BaggingClassifier
    * bootstrap
        * True : 배깅
        * False : 페이스팅
    * n_jobs=1 : 사용할 CPU 코어수, -1:최대한
* `sklearn.ensemble.RandomforestClassifier`
    * n_estimators : 생성할 트리의 갯수, 클수록 좋지만 훈련시간과 메모리 부담
        * 생성된 트리는 객체의 `estimator_` 속성에
    * random_state : 생성할 때 마다 달라 질수 있으므로 같은 결과를 원하면 값을 고정
    * max_fatures : 선택할 무작위 특성의 갯수, 핵심 변수, 기본값을 권장
        * 값이 크면 : 트리들이 비슷해짐
        * 값이 작으면 : 트리들이 달라지고 깊어진다.
*  sklearn.ensemble.GradientBoostingclassfier
    

#### 유방암 예제 , random forest

In [ ]:
# 책 intro_ml p119

from sklearn import model_selection
from sklearn import ensemble
from sklearn import datasets

cancer = datasets.load_breast_cancer()
X_train, X_test, y_train, y_test = model_selection.train_test_split(cancer.data,
                                                        cancer.target,
                                                        random_state=0)

forest = ensemble.RandomForestClassifier(n_estimators=100, random_state=0)
forest.fit(X_train, y_train)

print('Train Accuracy: %.3f%%'%(forest.score(X_train, y_train)*100))
print('Test Accuracy: %.3f%%'%( forest.score(X_test, y_test)*100))

#### 숫자 손글씨

In [ ]:
import numpy as np, cv2
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn import ensemble
import matplotlib.pyplot as plt

digits = load_digits()
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, random_state=0, test_size=0.3)

#tree = DecisionTreeClassifier(criterion='entropy')
tree = ensemble.RandomForestClassifier(n_estimators=100, random_state=0)
tree.fit(X_train,y_train)

print("Train Accuracy :", tree.score(X_train, y_train))
print("Test Accuracy1 :", tree.score(X_test, y_test))


In [ ]:
import sys
sys.path.append('..')
import img2data

image = cv2.imread('../img/0458.png')
plt.imshow(image)
plt.show()
numbers = img2data.img2digits(image, (8,8))
for i, n in enumerate(numbers):
    pred = tree.predict(n/255 * 16)
    plt.subplot(1, len(numbers), i+1)
    plt.title(str(pred))
    plt.imshow(n.reshape(8,8), cmap="gray")
    plt.axis("off")